### ISSUE TITLE
Header keys changing case

### ISSUE THREAD

**Issue by EricE** [Kyria/EsiPy#40] opened 2018-05-24 04:18 UTC
I've been grabbing xx.header['Expires'] to set a timer to scan my orders every 5 minutes.  With 0.4.0, my code is throwing a KeyError because 'Expires' is changing to 'expires'. I think it is happening with headers returned from the cache.

I looked through client.py and you are doing res.headers.get('expires') frequently but since it is from a case-insensitive dict it is working.  By the time it gets to my code, it is a pyswagger.io.Response which is case sensitive. 

Here are the headers for the first response and request:
  {'Accept': 'application/json'}

{'Date': ['Thu, 24 May 2018 03:19:13 GMT'], 'Content-Type': ['application/json; charset=UTF-8'], 'Content-Length': ['641'], 'Connection': ['keep-alive'], 'Access-Control-Allow-Credentials': ['true'], 'Access-Control-Allow-Headers': ['Content-Type,Authorization,If-None-Match,X-User-Agent'], 'Access-Control-Allow-Methods': ['GET,HEAD,OPTIONS'], 'Access-Control-Allow-Origin': ['*'], 'Access-Control-Expose-Headers': ['Content-Type,Warning,ETag,X-Pages,X-ESI-Error-Limit-Remain,X-ESI-Error-Limit-Reset'], 'Access-Control-Max-Age': ['600'], 'Allow': ['GET,HEAD,OPTIONS'], 'Cache-Control': ['public'], 'Content-Encoding': ['gzip'], 'Etag': ['"e15db176cd7960d74a0770861a4d5b444fadcbf2843e10e8bc2317ee"'], 'Expires': ['Thu, 24 May 2018 03:24:12 GMT'], 'Last-Modified': ['Thu, 24 May 2018 03:19:12 GMT'], 'Strict-Transport-Security': ['max-age=31536000'], 'Vary': ['Accept-Encoding'], 'X-Esi-Error-Limit-Remain': ['100'], 'X-Esi-Error-Limit-Reset': ['47'], 'X-Esi-Request-Id': ['485b8a1d-51d1-40b3-b28f-003a019f3bf8'], 'X-Pages': [1]}

Second pair:
    {'Accept': 'application/json', 'If-None-Match': '"e15db176cd7960d74a0770861a4d5b444fadcbf2843e10e8bc2317ee"'}

{'date': ['Thu, 24 May 2018 03:24:14 GMT'], 'Content-Type': ['application/json; charset=UTF-8'], 'Content-Length': ['641'], 'Connection': ['keep-alive'], 'Access-Control-Allow-Credentials': ['true'], 'Access-Control-Allow-Headers': ['Content-Type,Authorization,If-None-Match,X-User-Agent'], 'Access-Control-Allow-Methods': ['GET,HEAD,OPTIONS'], 'Access-Control-Allow-Origin': ['*'], 'Access-Control-Expose-Headers': ['Content-Type,Warning,ETag,X-Pages,X-ESI-Error-Limit-Remain,X-ESI-Error-Limit-Reset'], 'Access-Control-Max-Age': ['600'], 'Allow': ['GET,HEAD,OPTIONS'], 'Cache-Control': ['public'], 'Content-Encoding': ['gzip'], 'Etag': ['"e15db176cd7960d74a0770861a4d5b444fadcbf2843e10e8bc2317ee"'], 'expires': ['Thu, 24 May 2018 03:29:13 GMT'], 'Last-Modified': ['Thu, 24 May 2018 03:19:12 GMT'], 'Strict-Transport-Security': ['max-age=31536000'], 'Vary': ['Accept-Encoding'], 'X-Esi-Error-Limit-Remain': ['100'], 'X-Esi-Error-Limit-Reset': ['47'], 'X-Esi-Request-Id': ['485b8a1d-51d1-40b3-b28f-003a019f3bf8'], 'X-Pages': [1]}

Note that 'Expires' has gone to 'expires' in the response.  

It looks like it happens in client.py here:

    if res.status_code == 304 and cached_response is not None:
          cached_response.headers['expires'] = res.headers.get('expires')
          cached_response.headers['date'] = res.headers.get('date')
          return cached_response

Can this be changed to 'Expires' (and maybe date too)?

**Comment by Kyria** [comment] 2018-05-24 11:46
I will fix that yes, in case it changes anything.
Actually it's a bug pyswagger side because headers are case sensitive there (I already opened it). So when it'll be fixed, it'll also fix that issue :) 

Thanks for the report

**Comment by Kyria** [comment] 2018-05-24 13:44
Change have been released in 0.4.1. After some testing it looks like it works as expected now.

Thanks for the report, i will keep that issue open until pyswagger is updated to not forget to update pyswagger minimum version for esipy :)

**Comment by EricE** [comment] 2018-05-25 02:27
One note in case somebody else finds their way here, I had to delete the cache or else I got an error with 0.4.1 on line 88 of app.py, expires hadn't been assigned yet.  Worked fine with the new values.

**Comment by Kyria** [comment] 2018-05-25 08:27
this is... weird ? I didn't change anything at this location... I just made sure cache was updated in app.py if we had 304 :/

**Comment by EricE** [comment] 2018-05-27 17:51
It happened again...  It looks like cached_expiry is first set to 0 when the cache is new and then to timeout which is 24 hours later than the current time when it is stuck in the cache.  If 24 hours passes and the app is started again, it gets to line 79:

    if self.expire == 0 or cached_expiry >= time.time():

and cached_expiry < time.time() so it goes to the etag check and dies on line 88:

    if ((expires is None or cache_timeout < 0 or

expires wasn't set in line 68 since self.expire is always 86400 (in my usage at least).  I don't see a mechanism to refresh cached_expiry, shouldn't it update every time EsiApp is created?

**Comment by Kyria** [comment] 2018-05-27 22:31
Well, actually cached_expiry is updated when the cached value is updated, [here](https://github.com/Kyria/EsiPy/blob/master/esipy/app.py#L101) and [here](https://github.com/Kyria/EsiPy/blob/master/esipy/app.py#L108) (it's the timeout value).

I seem to have fixed that issue (cannot reproduce it anymore since the change)

It's released in 0.4.2 :)

**Comment by Kyria** [comment] 2018-07-02 09:02
as pyswagger fixed the case sensitive headers (to be case insensitive), i've updated the minimal pyswagger version required for esipy.
Now headers will be case insensitives :) 

released in 0.4.3

**Closed by Kyria** 2018-07-02 09:02 UTC
Labels: Bug, Staging, pyswagger
