### ISSUE TITLE
Swagger UrL 505

### ISSUE THREAD

**Issue by hditano** [Kyria/EsiPy#55] opened 2020-06-09 17:22 UTC
just got this error evertime i try to setup the script.

esipy.exceptions.APIException: HTTP Error 500: b'{"Message":"An error has occurred."}'

I'm using:

app = App.create(url="https://esi.evetech.net/latest/swagger.json")

**Comment by Kyria** [comment] 2020-06-10 09:45
`App.create` is from pyswagger... how can you have a EsiPy exception with that? 

What exactly are you doing ? Because I have no issue with the `App.create` thing if i try it manually...

**Comment by Kyria** [comment] 2020-06-15 07:43
i'm closing this as I can't reproduce it and due to the lack of information. 
Feel free to open again the issue if this still happen, but please include more information to be able to reproduce.

**Closed by Kyria** 2020-06-15 07:43 UTC
